### ISSUE TITLE
wrong parameter name used

### ISSUE THREAD

**Issue by thomsonjames** [f5devcentral/f5-big-iq-trial-quick-start#11]
Hi there, it looks like you have a capital "Q" instead of a lower case Q
https://github.com/f5devcentral/f5-big-iq-trial-quick-start/blob/7.1.0/azure/experimental/azure-deploy-with-existing-vnet.json

"bigIQPassword":{
            "type": "securestring",
            "minLength": 1,
            "metadata": {
            "description": "Password for BIG IQ DCD, CM instances."
            }

But later, you use

"bigIqPassword": "[parameters('bigIqPassword')]",

**Comment by rjouhann** [comment]
Good catch! I just fixed it. Thanks!!!
