### ISSUE TITLE
/config/cloud/setup-cm.sh and /config/cloud/setup-dcd.sh do not exist

### ISSUE THREAD

**Issue by jeff-crawford-std** [f5devcentral/f5-big-iq-trial-quick-start#13]
In Steps 6 and 7 on https://github.com/f5devcentral/f5-big-iq-trial-quick-start/tree/8.0.0/aws for F5 BIG-IQ Virtual Edition - (BYOL) Trial...

# /config/cloud/setup-dcd.sh
# /config/cloud/setup-cm.sh

...do not exist after the CFT successfully creates the F5 BIG-IQ Virtual Edition - (BYOL) Trial instances.

[admin@ip-<redacted>:NO LICENSE:Standalone] config # pwd
/config
[admin@ip-172-31-90-57:NO LICENSE:Standalone] config # ll
total 904
drwxr-xr-x. 4 root root   4096 Feb 19 14:20 aaa
drwxr-xr-x. 2 root root   4096 Mar 15 17:36 big3d
-r--r--r--. 1 root root 330341 Mar 15 17:36 BigDB.dat
drwxr-xr-x. 4 root root   4096 Mar 15 17:34 bigip
-rw-r-----. 1 root root   9676 Mar 15 17:35 bigip_base.conf
-rw-r--r--. 1 root  135   1242 Feb 19 14:25 bigip_base.conf.bak
-rw-r-----. 1 root root   6953 Mar 15 17:35 bigip.conf
-rw-r-----. 1 root root    397 Mar 15 17:35 bigip_user.conf
drwxr-xr-x. 2 root root   4096 Mar 15 17:33 bigpipe
-rw-r--r--. 1 root root     62 Feb 17 22:24 biq_provision.cfg
-r--r--r--. 1 root root   2393 Feb 19 11:32 cipher.conf
-rw-r--r--. 1 root root   9398 Mar 15 17:33 daemon.conf
drwxr-xr-x. 2 root root   4096 Feb 19 13:20 eav
drwxr-xr-x. 4 root root   4096 Feb 19 14:22 em
-r--r--r--. 1 root root    246 Mar 15 17:34 enhanced_core_files.conf
-r--r--r--. 1 root root    217 Feb 19 13:14 eventd.xml
drwxr-xr-x. 2 root root   4096 Feb 19 14:21 f5_public
drwxr-xr-x. 2 root root   4096 Feb 19 14:24 failover
drwxr-xr-x. 8 root root   4096 Mar 15 17:36 filestore
drwxr-xr-x. 2 root root   4096 Feb 19 12:18 gtm
drwxr-xr-x. 5 root root   4096 Feb 19 14:24 httpd
drwx------. 2 root root  16384 Feb 19 14:14 lost+found
-r--r--r--. 1 root root   3925 Feb 19 11:32 low_profile_base.conf
-rw-r--r--. 1 root root  18010 Mar 15 17:34 merged.conf
drwxr-xr-x. 2 root root   4096 Feb 19 14:24 monitors
drwxr-xr-x. 3 root root   4096 Mar 15 17:36 net-snmp
lrwxrwxrwx. 1 root root     26 Feb 19 14:23 ntp.conf -> ../var/run/config/ntp.conf
drwxr-xr-x. 2 root root   4096 Mar 15 17:33 partitions
drwxr-xr-t. 2 root root   4096 Mar 15 17:33 partitions.bak
-r--r--r--. 1 root root 161048 Feb 19 11:32 profile_base.conf
lrwxrwxrwx. 1 root root     26 Mar 15 17:33 rndc.key -> /var/named/config/rndc.key
drwxr-xr-x. 2 root root   4096 Feb 19 14:23 snmp
drwxr-xr-x. 2 root root   4096 Mar 15 17:33 ssh
drwxr-xr-x. 6 root root   4096 Mar 15 17:33 ssl
-r-xr-xr-x. 1 root root    281 Feb 19 11:32 startup
-rw-r--r--. 1 root root 247019 Mar 15 17:34 statsd.conf
-rwxr-xr-x. 1 root root     63 Feb 19 12:55 telemd_config.json
-rw-r--r--. 1 root root      0 Feb 19 13:30 user_alert.conf
[admin@ip-<redacted>:NO LICENSE:Standalone] config #
[admin@ip-172-31-90-57:NO LICENSE:Standalone] / # cat /VERSION
Product: BIG-IQ
Version: 8.0.0
Build: 0.0.594
Sequence: 8.0.0-0.0.594.0
BaseBuild: 0.0.594
Edition: Final
Date: Fri Feb 19 13:34:00 PST 2021
Built: 210219133400
Changelist: 3458319
JobID: 1276412
[admin@ip-172-31-90-57:NO LICENSE:Standalone] / #

**Comment by rjouhann** [comment]
@jeff-crawford-std  were you using (new VPC) or (existing VPC) CFT? I just found a missing double quote on the (new VPC) template I am going to fix now.

**Comment by rjouhann** [comment]
@jeff-crawford-std it should work now with both templates. Please re-open the issue if you are still seeing issues with the trial templates.

```
[admin@ip-10-1-1-97:NO LICENSE:Standalone] ~ # cd /config/cloud/
[admin@ip-10-1-1-97:NO LICENSE:Standalone] cloud # ls -lrt
total 8
-rwxr-xr-x. 1 root root 578 Mar 15 18:38 setup-dcd.sh
-rwxr-xr-x. 1 root root 680 Mar 15 18:38 setup-dcd-background.sh
[admin@ip-10-1-1-97:NO LICENSE:Standalone] cloud # exit

```

**Comment by jeff-crawford-std** [comment]
HI @rjouhann it's an existing VPC.  It's now working - all good.  Thank you for the quick response!
