### ISSUE TITLE
Make DCD optional

### ISSUE THREAD

**Issue by justinbeckham** [f5devcentral/f5-big-iq-trial-quick-start#14]
Hi Roman, sometimes customers need to deploy just BIG-IQ License Manager for ELA. Can you update this template to make the DCD optional?

**Comment by rjouhann** [comment]
Hello,

This isn't the intent of this repository to be used for production deployment or LM.

Please open up an issue here https://github.com/F5Networks/f5-aws-cloudformation instead.

Thanks & Regards,
Roman
