### ISSUE TITLE
DCD units only have "Web Application" Service enabled

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-big-iq-trial-quick-start#5]
**Feature Request**

The DCD unit only has Web Application service enabled, I've never found a reason to limit this, turning them all on by default will cause fewer issues later.

**Possible Fixes:**

POST to the DCD endpoint of the multiple services:
/mgmt/cm/websafe/tasks/add-listener/ 
Body: module: "websafe"

**Comment by rjouhann** [comment]
Fixed. Now enabling all services available on the DCD (asm access dos websafe ipsec afm)
