### ISSUE TITLE
Units DNS objects are auto set at 8.8.8.8 (same for NTP server)

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-big-iq-trial-quick-start#6]
**Feature Request**

DNS objects in the deployment units are set at 8.8.8.8. This works however it can be problematic for environments that are not using external dns (and may not allow that query out). This deployment should use the provider DNS objects.

This may only be needed in "existing" environments. 

Possible fix:

Query the metadata service for your local information, then post to the easy start API the output.

**Comment by rjouhann** [comment]
For **AWS**, using 169.254.169.123 for NTP (timezone set to UTC) and 169.254.169.253, 8.8.8.8 for DNS.
For **Azure**, using time.windows.com for NTP (timezone set to UTC).and 168.63.129.16, 8.8.8.8 for DNS.
