### ISSUE TITLE
Azure existing net fails with VNET resource failed not found Location

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-big-iq-trial-quick-start#8]
Deploying Azure quickstart BIG-IQ 7.1 using existing VNET.

https://github.com/f5devcentral/f5-big-iq-trial-quick-start/blob/7.1.0/azure/experimental/azure-deploy-with-existing-vnet.json

My new resource group name was giroux-bigiq. I left "Location" parameter as default which is [resourceGroup().location], and I get the below error.

Error:
```
The Resource 'Microsoft.Network/virtualNetworks/jgf5-1-vnet' under resource group 'giroux-bigiq' was not found.
```

This seems to be related to the vneId parameter. It is being saved, but it is NOT being used when creating the NICs. Therefore, the VNET is not found.
```
"vnetId": "[resourceId('Microsoft.Network/virtualNetworks', variables('virtualNetworkName'))]",
```

Also the subnet IDs for the NIC resources are incorrect

Mgmt example...
```
"subnet": {
  "id": "[reference(resourceId('Microsoft.Network/virtualNetworks',parameters('vnetName')),'2019-04-01').subnets[0].id]"
  }
```

Internal example...
```
"subnet": {
  "id": "[reference(resourceId('Microsoft.Network/virtualNetworks',parameters('vnetName')),'2019-04-01').subnets[1].id]"
  }
```

And...the NSG is causing issues too finding existing VNET name with current code...
```
"sourceAddressPrefix": "[reference(resourceId('Microsoft.Network/virtualNetworks',parameters('vnetName')),'2019-04-01').addressSpace.addressPrefixes[0]]",
```

**Comment by JeffGiroux** [comment]
The vnetId needs to be updates as well as the subnet IDs. Recommend looking at the F5 cloud templates for ARM BIG-IP deployments "existing net" for example code.
https://github.com/F5Networks/f5-azure-arm-templates/blob/df1c759377b5112b03236b1292ff6cff2fcb2bf7/supported/standalone/3nic/existing-stack/payg/azuredeploy.json#L449

Workaround...

1. Update vNetId
```
"vnetId": "[resourceId(parameters('vnetResourceGroupName'),'Microsoft.Network/virtualNetworks',variables('virtualNetworkName'))]",
```
2. Update subnet IDs (there are 4: 2 for mgmt, 2 for internal)
mgmt
```
"subnet": {
  "id": "[concat(variables('vnetId'), '/subnets/', parameters('mgmtSubnetName'))]"
}
```
internal
```
"subnet": {
  "id": "[concat(variables('vnetId'), '/subnets/', parameters('internalSubnetName'))]"
}
```
3. Update the NSG
```
"sourceAddressPrefix": "[reference(variables('vnetId'),'2019-04-01').addressSpace.addressPrefixes[0]]",
```

**Comment by rjouhann** [comment]
fixed
