### ISSUE TITLE
Using custom DNS servers on the Azure VNet with the missing 168.63.129.16

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/f5-big-iq-trial-quick-start#9]
Regarding  https://cdn.f5.com/product/bugtracker/ID719241.html, 

Specific to the custom DNS question…
This is involved…
https://github.com/F5Networks/f5-azure-arm-templates/issues/86#issuecomment-482735484

```
"dnsSettings": { "dnsServers": [ "168.63.129.16" ] }
```

…applied to the NIC resource.
 
To make it more automated, you could create a input parameter asking “Are you using custom DNS or DHCP”. Depending on how they answer, you could dynamically add the dnsServer or null it. Copy other “if” similar checks in your template. Not sure if having dnsServers with a “null” value works or not…but worth a try. Haven’t tested. But…something like…
 
1. Create new input for “Using Custom DNS?”
 
```
        "customDNS": {
            "defaultValue": "OPTIONAL",
            "metadata": {
                "description": "Select Yes if you are using your own DNS server instead of the Azure DHCP supplied DNS server.”
            },
            "type": "string"
        },
 
```
2. Null value if “No”
```
"customDNS": "[replace(parameters('customDNS'), OPTIONAL, '')]",
```
 
3. Edit network interface resource in template

https://github.com/f5devcentral/f5-big-iq-trial-quick-start/blob/5c55edbe147bf4ba71f2532850751082ef158f06/azure/experimental/azure-deploy-with-existing-vnet.json#L369
 
reference: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2019-04-01/networkinterfaces#NetworkInterfaceDnsSettings
 
Your big-iq template code…(snippet example). Add dnsSettings on same indent as ipConfigurations and networkSecurityGroup.

```
        {
            "type": "Microsoft.Network/networkInterfaces",
            "name": "[variables('mgmtNicName')]",
            "apiVersion": "[variables('networkApiVersion')]",
            "location": "[variables('location')]",
            "tags": "[if(empty(variables('tagValues')), json('null'), variables('tagValues'))]",
            "properties": {
                "ipConfigurations": [--snippet--],
                "networkSecurityGroup": {--snippet--}
                "dnsSettings": {
                    "dnsServers": [ "[if(variables('customDNS'), “168.63.129.16”, json('null'))]" ]
                }
            },
            "dependsOn": [--snippet--]
        },
```
 
Flow…
1. You ask user if they are using custom dns
2. Resource creation starts
3. Dns settings are validated
4. Is customDNS value present?
4.a If yes, dnsServers=168.63.129.16
4.b Else dnsServers=null
 
Step 4b needs to be tested. Based on Azure docs…the object doesn’t have to exist. But…if the object exists, then the array must not be blank…I’m guessing.
 
“List of DNS servers IP addresses. Use 'AzureProvidedDNS' to switch to azure provided DNS resolution. 'AzureProvidedDNS' value cannot be combined with other IPs, it must be the only value in dnsServers collection. – string”
 
With that in mind, maybe you do this “if” check…
```
"dnsServers": [ "[if(variables('customDNS'), “168.63.129.16”, “AzureProvidedDNS”)]" ]
```

So…if customDNS contains Yes, then custom DNS is being used. Therefore, dnsServers has value 168.63.129.16. Else, dnsServers will use value AzureProvidedDNS which tells the resource exacly that.

**Comment by rjouhann** [comment]
@JeffGiroux 

I tried to implement this but I was not able to use AzureProvidedDNS. 

However, I am not sure why we would set “168.63.129.16” as the “AzureProvidedDNS” default should be 168.63.129.16. Going back on work around described [ID719241](https://cdn.f5.com/product/bugtracker/ID719241.html) it says:

> Add 168.63.129.16 route on mgmt interface during BIG-IP or BIG-IQ system initialization to facilitate correct waagent custom script extension execution.

**Comment by JeffGiroux** [comment]
Well, that would make sense. I had to do that for my article write-up when testing a BIG-IP v12.

See https://devcentral.f5.com/s/articles/Using-Cloud-Templates-to-Change-BIG-IP-Versions-Azure and reference section...
"Example Edits for Option #3a: Edit Latest Template to Change BIG-IP Versions 12.x"

I add the route to mgmt during onboarding when using version v12.

I set routeCmd...
```
"routeCmd": "[concat('tmsh create sys management-route waagent_route network 168.63.129.16/32 gateway ', variables('mgmtRouteGw'), '; tmsh save sys config')]",
```

Then use it later in the extensions script call...
```
                    "commandToExecute": "[concat('function cp_logs() { cd /var/lib/waagent/custom-script/download && cp `ls -r | head -1`/std* /var/log/cloud/azure; cd /var/log/cloud/azure && cat stdout stderr > install.log; }; CLOUD_LIB_DIR=/config/cloud/azure/node_modules/@f5devcentral; mkdir -p $CLOUD_LIB_DIR && cp f5-cloud-libs*.tar.gz* /config/cloud; mkdir -p /var/config/rest/downloads && cp ', variables('f5AS3Build'), ' /var/config/rest/downloads; mkdir -p /var/log/cloud/azure; /usr/bin/install -m 400 /dev/null /config/cloud/.passwd; /usr/bin/install -b -m 755 /dev/null /config/verifyHash; /usr/bin/install -b -m 755 /dev/null /config/installCloudLibs.sh; IFS=', variables('singleQuote'), '%', variables('singleQuote'), '; echo -e ', variables('verifyHash'), ' > /config/verifyHash; echo -e ', variables('installCloudLibs'), ' > /config/installCloudLibs.sh; echo -e ', variables('appScript'), ' | /usr/bin/base64 -d > /config/cloud/deploy_app.sh; chmod +x /config/cloud/deploy_app.sh; echo -e ', variables('installCustomConfig'), ' >> /config/customConfig.sh; unset IFS; bash /config/installCloudLibs.sh; source $CLOUD_LIB_DIR/f5-cloud-libs/scripts/util.sh; encrypt_secret ', variables('singleQuote'), variables('adminPasswordOrKey'), variables('singleQuote'), ' \"/config/cloud/.passwd\" true; $CLOUD_LIB_DIR/f5-cloud-libs/scripts/createUser.sh --user svc_user --password-file /config/cloud/.passwd --password-encrypted; ', variables('allowUsageAnalytics')[parameters('allowUsageAnalytics')].hashCmd, '; /usr/bin/f5-rest-node $CLOUD_LIB_DIR/f5-cloud-libs/scripts/onboard.js --no-reboot --output /var/log/cloud/azure/onboard.log --signal ONBOARD_DONE --log-level info --cloud azure --install-ilx-package file:///var/config/rest/downloads/', variables('f5AS3Build'), ' --host ', reference(variables('mgmtNicId')).ipConfigurations[0].properties.privateIPAddress, ' --ssl-port ', variables('bigIpMgmtPort'), ' -u svc_user --password-url file:///config/cloud/.passwd --password-encrypted --hostname ', concat(variables('instanceName'), '.', variables('location'), '.cloudapp.azure.com'),  ' --ntp ', parameters('ntpServer'), ' --tz ', parameters('timeZone'), ' --modules ', parameters('bigIpModules'), ' --db tmm.maxremoteloglength:2048', variables('allowUsageAnalytics')[parameters('allowUsageAnalytics')].metricsCmd, '; tmsh modify sys software update auto-phonehome ', variables('allowPhoneHome'), '; /usr/bin/f5-rest-node $CLOUD_LIB_DIR/f5-cloud-libs/scripts/network.js --output /var/log/cloud/azure/network.log --wait-for ONBOARD_DONE --host ', reference(variables('mgmtNicId')).ipConfigurations[0].properties.privateIPAddress, ' --port ', variables('bigIpMgmtPort'), ' -u svc_user --password-url file:///config/cloud/.passwd --password-encrypted --default-gw ', variables('tmmRouteGw'), ' --vlan name:external,nic:1.1 --vlan name:internal,nic:1.2 --self-ip name:self_2nic,address:', variables('extSubnetPrivateAddress'), ',vlan:external --self-ip name:self_3nic,address:', variables('intSubnetPrivateAddress'), ',vlan:internal --log-level info', '; if [[ $? == 0 ]]; then tmsh load sys application template f5.service_discovery.tmpl; tmsh load sys application template f5.cloud_logger.v1.0.0.tmpl; ', variables('routeCmd'), '; echo -e ', variables('routeCmd'), ' >> /config/startup; bash /config/cloud/deploy_app.sh ', variables('commandArgs'), ' ; bash /config/customConfig.sh; $(cp_logs); else $(cp_logs); exit 1; fi', '; if grep -i \"PUT failed\" /var/log/waagent.log -q; then echo \"Killing waagent exthandler, daemon should restart it\"; pkill -f \"python -u /usr/sbin/waagent -run-exthandlers\"; fi')]"
```

I have no additional "dnsSettings" or "dnsServers" for my v12. So...add a route during onboarding and you should be good.

**Comment by rjouhann** [comment]
fixed

**Comment by rjouhann** [comment]
re-opening, still not working. looking on how to implement fix.

**Comment by rjouhann** [comment]
Adding the route doesn't help. I have removed it and added the original solution:

```
"dnsSettings": "[if(variables('customDNS'),json('{\"dnsServers\": [ \"168.63.129.16\" ] }'),'\"AzureProvidedDNS\"')]"
```

Added a new **customDNS** variable in the _existing VNET_ template.
